<?php

namespace GestionComBundle\Repository;

/**
 * comdRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class comdRepository extends \Doctrine\ORM\EntityRepository
{
}
