<?php

namespace GestionComBundle\Repository;

/**
 * Panier_ProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Panier_ProduitRepository extends \Doctrine\ORM\EntityRepository
{
}
