<?php

namespace GestionComBundle\Repository;

/**
 * panierrRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class panierrRepository extends \Doctrine\ORM\EntityRepository
{
}
